name: CI

on:
  push:
    branches: [ "main", "analyze" ]
  pull_request:
    branches: [ "main", "analyze" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        id: lint
        run: make lint
        continue-on-error: true

      - name: Update Badges
        id: update_badges
        run: |
          sed -i 's/failure/![CI](https:\/\/img.shields.io\/badge\/Install-Success-green.svg)/g' README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action";
          git add README.md
          git commit -am "Updte README.md"
          git push 


    