name: CI

on:
  push:
    branches: [ "main", "analyze" ]
  pull_request:
    branches: [ "main", "analyze" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        id: lint
        run: make lint
        continue-on-error: true

      - name: Test
        id: test
        run: make test
        continue-on-error: true

      - name: Format
        id: format
        run: make format
        continue-on-error: true

      - name: Update Badges
        id: update_badges
        run: |
          if [ ${{ steps.lint.outcome }} == failure ]; then
            sed -i 's/!\[Lint\].*\.svg)/\!\[Lint\](https:\/\/img.shields.io\/badge\/Lint-Failure-red.svg)/g' README.md
          else
            sed -i 's/!\[Lint\].*\.svg)/\!\[Lint\](https:\/\/img.shields.io\/badge\/Lint-Success-green.svg)/g' README.md
          fi
          if [ ${{ steps.test.outcome }} == failure ]; then
            sed -i 's/!\[Test\].*\.svg)/\!\[Test\](https:\/\/img.shields.io\/badge\/Test-Failure-red.svg)/g' README.md
          else
            sed -i 's/!\[Test\].*\.svg)/\!\[Test\](https:\/\/img.shields.io\/badge\/Test-Success-green.svg)/g' README.md
          fi
          if [ ${{ steps.format.outcome }} == failure ]; then
            sed -i 's/!\[Format\].*\.svg)/\!\[Format\](https:\/\/img.shields.io\/badge\/Format-Failure-red.svg)/g' README.md
          else
            sed -i 's/!\[Format\].*\.svg)/\!\[Format\](https:\/\/img.shields.io\/badge\/Format-Success-green.svg)/g' README.md
          fi
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action";
          git add README.md
          git commit -am "Updte README.md"
          git push
        continue-on-error: true


    