name: CI

on:
  push:
    branches: [ "main", "analyze" ]
  pull_request:
    branches: [ "main", "analyze" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        id: install
        run: make install
        continue-on-error: true

      - name: Lint
        id: lint
        run: make lint
        continue-on-error: true

      - name: Test
        id: test
        run: make test
        continue-on-error: true

      - name: Format
        id: format
        run: make format
        continue-on-error: true

      - name: Generate Badges
        id: generate_badges
        run: |
          if [ ${{ steps.install.outcome }} == 'success' ]; then
            echo "https://img.shields.io/badge/Install-Success-green.svg" >> "$INSTALL_BADGE"
          else
            echo "https://img.shields.io/badge/Install-Failure-red.svg" >> "$INSTALL_BADGE"
          fi

          if [ ${{ steps.lint.outcome }} == 'success' ]; then
            echo "https://img.shields.io/badge/Lint-Success-green.svg" >> "$LINT_BADGE"
          else
            echo "https://img.shields.io/badge/Lint-Failure-red.svg" >> "$LINT_BADGE"
          fi

          if [ ${{ steps.test.outcome }} == 'success' ]; then
            echo "https://img.shields.io/badge/Test-Success-green.svg" >> "$TEST_BADGE"
          else
            echo "https://img.shields.io/badge/Test-Failure-red.svg" >> "$TEST_BADGE"
          fi

          if [ ${{ steps.format.outcome }} == 'success' ]; then
            echo "https://img.shields.io/badge/Format-Success-green.svg" >> "$FORMAT_BADGE"
          else
            echo "https://img.shields.io/badge/Format-Failure-red.svg" >> "$FORMAT_BADGE"
          fi
        
      - name: Update Badges
        id: update_badges
        run: echo "whatever" >> README.md

    