name: CI
on:
  push:
    branches: [ "main", "analyze"]
  pull_request:
    branches: [ "main", "analyze" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      
      - name: Generate Badges
        id: generate_badges
        run: |
          echo "::set-env name=INSTALL_BADGE::https://img.shields.io/badge/Install-Success-green.svg"
          echo "::set-env name=LINT_BADGE::https://img.shields.io/badge/Lint-Success-green.svg"
          echo "::set-env name=TEST_BADGE::https://img.shields.io/badge/Test-Success-green.svg"
          echo "::set-env name=FORMAT_BADGE::https://img.shields.io/badge/Format-Success-green.svg"

      - name: Output Badges
        run: |
          echo "Install Badge: $INSTALL_BADGE"
          echo "Lint Badge: $LINT_BADGE"
          echo "Test Badge: $TEST_BADGE"
          echo "Format Badge: $FORMAT_BADGE"