name: CI
on:
  push:
    branches: [ "main", "analyze"]
  pull_request:
    branches: [ "main", "analyze" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
