name: CI

on:
  push:
    branches: [ "main", "analyze" ]
  pull_request:
    branches: [ "main", "analyze" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Packages
        id: install
        run: make install
        continue-on-error: true

      - name: Lint
        id: lint
        run: make lint
        continue-on-error: true

      - name: Test
        id: test
        run: make test
        continue-on-error: true

      - name: Format
        id: format
        run: make format
        continue-on-error: true

      - name: Generate Badges
        id: generate_badges
        run: |
          OUTCOME_INSTALL=success
          if [ ${{ steps.install.outcome }} != 'success' ]; then
            OUTCOME_INSTALL=failure
          fi
          echo "::set-output name=INSTALL_BADGE::https://img.shields.io/badge/Install-$OUTCOME_INSTALL-{$OUTCOME_INSTALL}.svg"

          OUTCOME_LINT=success
          if [ ${{ steps.lint.outcome }} != 'success' ]; then
            OUTCOME_LINT=failure
          fi
          echo "::set-output name=LINT_BADGE::https://img.shields.io/badge/Lint-$OUTCOME_LINT-{$OUTCOME_LINT}.svg"

          OUTCOME_TEST=success
          if [ ${{ steps.test.outcome }} != 'success' ]; then
            OUTCOME_TEST=failure
          fi
          echo "::set-output name=TEST_BADGE::https://img.shields.io/badge/Test-$OUTCOME_TEST-{$OUTCOME_TEST}.svg"

          OUTCOME_FORMAT=success
          if [ ${{ steps.format.outcome }} != 'success' ]; then
            OUTCOME_FORMAT=failure
          fi
          echo "::set-output name=FORMAT_BADGE::https://img.shields.io/badge/Format-$OUTCOME_FORMAT-{$OUTCOME_FORMAT}.svg"

      - name: Output Badges
        run: |
          echo "Install Badge: ${{ steps.generate_badges.outputs.INSTALL_BADGE }}"
          echo "Lint Badge: ${{ steps.generate_badges.outputs.LINT_BADGE }}"
          echo "Test Badge: ${{ steps.generate_badges.outputs.TEST_BADGE }}"
          echo "Format Badge: ${{ steps.generate_badges.outputs.FORMAT_BADGE }}"